package ru.itmo.hhprocess.security;

public enum Privilege {
    PROFILE_VIEW,
    NOTIFICATION_VIEW,
    NOTIFICATION_MARK_READ,
    APPLICATION_CREATE,
    APPLICATION_VIEW_OWN,
    APPLICATION_RESPOND_INVITATION_OWN,
    VACANCY_CREATE,
    VACANCY_VIEW_OWN,
    VACANCY_UPDATE_OWN,
    APPLICATION_VIEW_ASSIGNED,
    APPLICATION_REJECT_ASSIGNED,
    APPLICATION_INVITE_ASSIGNED,
    JOB_RUN_TIMEOUT_CLOSE,
    SCHEDULE_VIEW_OWN
}
