spring:
  application:
    name: hh-process
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?currentSchema=${POSTGRES_SCHEMA}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: ${POSTGRES_SCHEMA}
        transaction:
          coordinator_class: jta
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0
    schemas: ${POSTGRES_SCHEMA}
  jackson:
    property-naming-strategy: SNAKE_CASE

server:
  port: ${SERVER_PORT:8080}

springdoc:
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized

narayana:
  log-dir: ${NARAYANA_LOG_DIR:${user.dir}/transaction-logs}
  default-timeout: ${NARAYANA_DEFAULT_TIMEOUT:60}
  node-identifier: ${NARAYANA_NODE_IDENTIFIER:hh-process}
  shorten-node-identifier-if-necessary: true

app:
  openapi:
    title: @project.name@
    version: @project.version@
    description: @project.description@
  security:
    users-xml-path: ${APP_SECURITY_USERS_XML:${user.dir}/data/users.xml}

  websocket:
    allowed-origins: ${WS_ALLOWED_ORIGINS:http://localhost:3000}
  timeout:
    debug:
      disable-notifications: ${APP_TIMEOUT_DEBUG_DISABLE_NOTIFICATIONS:false}


logging:
  level:
    org.springframework.transaction: TRACE
    org.springframework.orm.jpa: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.type.descriptor.sql: TRACE
    org.hibernate.engine.transaction.internal.TransactionImpl: DEBUG
    com.arjuna: DEBUG
    com.arjuna.ats: DEBUG
    org.jboss.narayana: DEBUG
    ru.itmo.hhprocess.service.TimeoutService: DEBUG
    ru.itmo.hhprocess.service.TimeoutBatchProcessor: DEBUG
    ru.itmo.hhprocess.service.ScheduleService: DEBUG
    ru.itmo.hhprocess.controller.AdminController: DEBUG
