package ru.itmo.hhprocess.enums;

public enum ErrorCode {
    AUTH_INVALID_CREDENTIALS,
    AUTH_ACCESS_DENIED,
    USER_ALREADY_EXISTS,
    VACANCY_NOT_FOUND,
    VACANCY_NOT_ACTIVE,
    APPLICATION_NOT_FOUND,
    APPLICATION_ALREADY_EXISTS,
    INVALID_APPLICATION_STATE,
    INVALID_VACANCY_STATE,
    INVITATION_EXPIRED,
    NOTIFICATION_NOT_FOUND,
    VALIDATION_ERROR,
    INTERNAL_ERROR,
    NOT_FOUND,
    INTERVIEW_NOT_FOUND,
    SCHEDULE_SLOT_CONFLICT
}
