package ru.itmo.hhprocess.enums;

public enum NotificationType {
    SCREENING_RESULT,
    SCREENING_ERROR,
    NEW_APPLICATION,
    APPLICATION_REJECTED,
    INVITATION,
    INVITATION_RESPONSE,
    INVITATION_TIMEOUT,
    INTERVIEW_CANCELLED,
    VACANCY_CLOSED
}
